name: env_indicator
description: A Flutter widget that visually shows the current device info and app environment on every page.
  (i.e. DEV/QA, but not in PROD)
version: 0.9.3+25
homepage: https://github.com/cavecafe-cc/env_indicator
repository: https://github.com/cavecafe-cc/env_indicator
issue_tracker: https://github.com/cavecafe-cc/env_indicator/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0